### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by toboho** [bitcoinnano/Bitcoin-Nano#1]
。。。

**Comment by bitcoinnano** [comment]
你好，
我试验了下可以编译，配置如下：
root@ubuntu:~/bak/Bitcoin-Nano# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2692 v2 @ 2.20GHz
Stepping:              4
CPU MHz:               2199.998
BogoMIPS:              4399.99
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm vnmi ept fsgsbase tsc_adjust smep erms xsaveopt

**Comment by toboho** [comment]
好多人试了，都是缺少文件

**Comment by bitcoinnano** [comment]
需要把libsodium.a放在/usr/local/lib/libsodium.a， 头文件放在/usr/local/include下

**Comment by toboho** [comment]
钱包文件给我发一份行不xinyicom@gmail.com

**Comment by bitcoinnano** [comment]
稍等，会在这更新可运行程序，好了放链接。

**Comment by bitcoinnano** [comment]
@toboho 
[linux full node](https://github.com/bitcoinnano/Bitcoin-Nano/releases/download/v0.15.0.2/btcnano_elf.tgz)
