### ISSUE TITLE
预挖几百万个还不够？还不放出来？

### ISSUE THREAD

**Issue by toboho** [bitcoinnano/Bitcoin-Nano#2]
This issue tracker is only for technical issues related to btcnano-core.

General btcnano questions and/or support requests and are best directed to the [Btcnano StackExchange](https://btcnano.stackexchange.com).

For reporting security issues, please read instructions at [https://btcnanocore.org/en/contact/](https://btcnanocore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of btcnano-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by bitcoinnano** [comment]
We do not pre-mining. The software and pool will be released on the offical website as soon as possible. We hide nothing, and we do not participate mining.

**Comment by bitcoinnano** [comment]
We released the pool on the offical website. You can use our software or claymore or ewrf to mining.
